'use client';
import {useEffect,useMemo,useState} from 'react'; import {timeline,cluster,trigger,status} from '../lib/api';
export default function Home(){const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[sources,setSources]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
const load=async()=>{try{setError('');setItems(await timeline())}catch(e){setError(e.message)}}; useEffect(()=>{load()},[]);
const allSources=useMemo(()=>[...new Set(items.flatMap(i=>i.sources||[]))].sort(),[items]); const active=sources.length?sources:allSources; const filtered=items.filter(i=>!(i.sources||[]).length||(i.sources||[]).some(s=>active.includes(s)));
async function open(id){try{setSelected(await cluster(id))}catch(e){setError(e.message)}}
async function refresh(){setBusy(true);try{const j=await trigger();for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,2000));const s=await status(j.jobId);if(s.status==='completed'){await load();break}if(s.status==='failed')throw new Error('Ingestion failed')} }catch(e){setError(e.message)}finally{setBusy(false)}}
function toggle(s){setSources(prev=>{const base=prev.length?prev:allSources;return base.includes(s)?base.filter(x=>x!==s):[...base,s]})}
return <main><header><div><p className="eyebrow">LIVE INTELLIGENCE</p><h1>News Pulse</h1><p className="sub">Topic-clustered news, mapped across time.</p></div><button onClick={refresh} disabled={busy}>{busy?'Refreshing…':'↻ Refresh data'}</button></header>
<section className="filters"><span>Sources</span>{allSources.map(s=><label key={s}><input type="checkbox" checked={active.includes(s)} onChange={()=>toggle(s)}/>{s}</label>)}</section>{error&&<p className="error">{error}</p>}
<section className="panel"><div className="panelHead"><div><h2>Topic timeline</h2><p>{filtered.length} active clusters</p></div><div className="axis">Earlier <span>→</span> Latest</div></div><div className="timeline">{filtered.map((x,i)=><button className="event" key={x.id} onClick={()=>open(x.id)} style={{'--w':`${Math.min(96,36+x.articleCount*9)}%`}}><span className="dot"/><div className="eventCard"><div className="meta">{new Date(x.start).toLocaleString()} · {x.articleCount} article{x.articleCount===1?'':'s'}</div><strong>{x.label}</strong><div className="bar"><i/></div><small>{(x.sources||[]).join(' · ')||'Mixed sources'}</small></div></button>)}</div></section>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">CLUSTER DETAIL</p><h2>{selected.label}</h2><p>{selected.articleCount} articles · {new Date(selected.startTime).toLocaleString()} — {new Date(selected.endTime).toLocaleString()}</p><div className="articles">{selected.articles.map(a=><a href={a.url} target="_blank" rel="noreferrer" key={a.articleId}><span>{a.source} · {new Date(a.publishedAt).toLocaleString()}</span><strong>{a.title}</strong><p>{a.summary?.slice(0,180)}</p></a>)}</div></aside></div>}</main>}
